INSERT INTO [Rocket21].[dbo].[DraftLogs]
           ([content_picker_id]
           ,[sender_name]
           ,[icon_url]
           ,[wrapper_text]
           ,[title]
           ,[body]
           ,[media_text]
           ,[created_at]
           ,[media_type]
           ,[updated_by]
           ,[update_notes]
           ,[updated_at])
  select   [content_picker_id]
           ,[sender_name]
           ,[icon_url]
           ,[wrapper_text]
           ,[title]
           ,[body]
           ,[media_text]
           ,[created_at]
           ,[media_type]
           ,[updated_by]
           ,[update_notes]
           ,[updated_at]
           from [Rocket21].[dbo].[DraftLogs]
           where id = 123
           order by id desc
           